project_id = "aafobycbxitrgffqouro"

[functions.ai-generate]
verify_jwt = true

[functions.youtube-search]
verify_jwt = true

[functions.tutor-chat]
verify_jwt = true

[functions.web-search]
verify_jwt = true

[functions.image-search]
verify_jwt = true
