/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeToolRouteImport } from './routes/youtube-tool'
import { Route as TryRouteImport } from './routes/try'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NewRouteImport } from './routes/new'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdaptiveRouteImport } from './routes/adaptive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as DeeplearnIndexRouteImport } from './routes/deeplearn.index'
import { Route as AdaptiveIndexRouteImport } from './routes/adaptive.index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as MindmapPlanIdRouteImport } from './routes/mindmap.$planId'
import { Route as LearnPlanIdRouteImport } from './routes/learn.$planId'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as FlashcardsPlanIdRouteImport } from './routes/flashcards.$planId'
import { Route as DeeplearnPlanIdRouteImport } from './routes/deeplearn.$planId'
import { Route as CertificatePlanIdRouteImport } from './routes/certificate.$planId'
import { Route as AdaptiveSessionIdRouteImport } from './routes/adaptive.$sessionId'
import { Route as QuizPlanIdDayRouteImport } from './routes/quiz.$planId.$day'

const YoutubeToolRoute = YoutubeToolRouteImport.update({
  id: '/youtube-tool',
  path: '/youtube-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveRoute = AdaptiveRouteImport.update({
  id: '/adaptive',
  path: '/adaptive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsRoute,
} as any)
const DeeplearnIndexRoute = DeeplearnIndexRouteImport.update({
  id: '/deeplearn/',
  path: '/deeplearn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveIndexRoute = AdaptiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdaptiveRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MindmapPlanIdRoute = MindmapPlanIdRouteImport.update({
  id: '/mindmap/$planId',
  path: '/mindmap/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPlanIdRoute = LearnPlanIdRouteImport.update({
  id: '/learn/$planId',
  path: '/learn/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)
const FlashcardsPlanIdRoute = FlashcardsPlanIdRouteImport.update({
  id: '/flashcards/$planId',
  path: '/flashcards/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeeplearnPlanIdRoute = DeeplearnPlanIdRouteImport.update({
  id: '/deeplearn/$planId',
  path: '/deeplearn/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatePlanIdRoute = CertificatePlanIdRouteImport.update({
  id: '/certificate/$planId',
  path: '/certificate/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptiveSessionIdRoute = AdaptiveSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AdaptiveRoute,
} as any)
const QuizPlanIdDayRoute = QuizPlanIdDayRouteImport.update({
  id: '/quiz/$planId/$day',
  path: '/quiz/$planId/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adaptive': typeof AdaptiveRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRouteWithChildren
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/try': typeof TryRoute
  '/youtube-tool': typeof YoutubeToolRoute
  '/adaptive/$sessionId': typeof AdaptiveSessionIdRoute
  '/certificate/$planId': typeof CertificatePlanIdRoute
  '/deeplearn/$planId': typeof DeeplearnPlanIdRoute
  '/flashcards/$planId': typeof FlashcardsPlanIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/learn/$planId': typeof LearnPlanIdRoute
  '/mindmap/$planId': typeof MindmapPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/adaptive/': typeof AdaptiveIndexRoute
  '/deeplearn/': typeof DeeplearnIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/quiz/$planId/$day': typeof QuizPlanIdDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/try': typeof TryRoute
  '/youtube-tool': typeof YoutubeToolRoute
  '/adaptive/$sessionId': typeof AdaptiveSessionIdRoute
  '/certificate/$planId': typeof CertificatePlanIdRoute
  '/deeplearn/$planId': typeof DeeplearnPlanIdRoute
  '/flashcards/$planId': typeof FlashcardsPlanIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/learn/$planId': typeof LearnPlanIdRoute
  '/mindmap/$planId': typeof MindmapPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/adaptive': typeof AdaptiveIndexRoute
  '/deeplearn': typeof DeeplearnIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/quiz/$planId/$day': typeof QuizPlanIdDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adaptive': typeof AdaptiveRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRouteWithChildren
  '/new': typeof NewRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/try': typeof TryRoute
  '/youtube-tool': typeof YoutubeToolRoute
  '/adaptive/$sessionId': typeof AdaptiveSessionIdRoute
  '/certificate/$planId': typeof CertificatePlanIdRoute
  '/deeplearn/$planId': typeof DeeplearnPlanIdRoute
  '/flashcards/$planId': typeof FlashcardsPlanIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/learn/$planId': typeof LearnPlanIdRoute
  '/mindmap/$planId': typeof MindmapPlanIdRoute
  '/shared/$token': typeof SharedTokenRoute
  '/adaptive/': typeof AdaptiveIndexRoute
  '/deeplearn/': typeof DeeplearnIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/quiz/$planId/$day': typeof QuizPlanIdDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adaptive'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/new'
    | '/notes'
    | '/settings'
    | '/templates'
    | '/try'
    | '/youtube-tool'
    | '/adaptive/$sessionId'
    | '/certificate/$planId'
    | '/deeplearn/$planId'
    | '/flashcards/$planId'
    | '/groups/$id'
    | '/learn/$planId'
    | '/mindmap/$planId'
    | '/shared/$token'
    | '/adaptive/'
    | '/deeplearn/'
    | '/groups/'
    | '/quiz/$planId/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/new'
    | '/notes'
    | '/settings'
    | '/templates'
    | '/try'
    | '/youtube-tool'
    | '/adaptive/$sessionId'
    | '/certificate/$planId'
    | '/deeplearn/$planId'
    | '/flashcards/$planId'
    | '/groups/$id'
    | '/learn/$planId'
    | '/mindmap/$planId'
    | '/shared/$token'
    | '/adaptive'
    | '/deeplearn'
    | '/groups'
    | '/quiz/$planId/$day'
  id:
    | '__root__'
    | '/'
    | '/adaptive'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/groups'
    | '/new'
    | '/notes'
    | '/settings'
    | '/templates'
    | '/try'
    | '/youtube-tool'
    | '/adaptive/$sessionId'
    | '/certificate/$planId'
    | '/deeplearn/$planId'
    | '/flashcards/$planId'
    | '/groups/$id'
    | '/learn/$planId'
    | '/mindmap/$planId'
    | '/shared/$token'
    | '/adaptive/'
    | '/deeplearn/'
    | '/groups/'
    | '/quiz/$planId/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptiveRoute: typeof AdaptiveRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  NewRoute: typeof NewRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TryRoute: typeof TryRoute
  YoutubeToolRoute: typeof YoutubeToolRoute
  CertificatePlanIdRoute: typeof CertificatePlanIdRoute
  DeeplearnPlanIdRoute: typeof DeeplearnPlanIdRoute
  FlashcardsPlanIdRoute: typeof FlashcardsPlanIdRoute
  LearnPlanIdRoute: typeof LearnPlanIdRoute
  MindmapPlanIdRoute: typeof MindmapPlanIdRoute
  SharedTokenRoute: typeof SharedTokenRoute
  DeeplearnIndexRoute: typeof DeeplearnIndexRoute
  QuizPlanIdDayRoute: typeof QuizPlanIdDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-tool': {
      id: '/youtube-tool'
      path: '/youtube-tool'
      fullPath: '/youtube-tool'
      preLoaderRoute: typeof YoutubeToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive': {
      id: '/adaptive'
      path: '/adaptive'
      fullPath: '/adaptive'
      preLoaderRoute: typeof AdaptiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/deeplearn/': {
      id: '/deeplearn/'
      path: '/deeplearn'
      fullPath: '/deeplearn/'
      preLoaderRoute: typeof DeeplearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive/': {
      id: '/adaptive/'
      path: '/'
      fullPath: '/adaptive/'
      preLoaderRoute: typeof AdaptiveIndexRouteImport
      parentRoute: typeof AdaptiveRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindmap/$planId': {
      id: '/mindmap/$planId'
      path: '/mindmap/$planId'
      fullPath: '/mindmap/$planId'
      preLoaderRoute: typeof MindmapPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$planId': {
      id: '/learn/$planId'
      path: '/learn/$planId'
      fullPath: '/learn/$planId'
      preLoaderRoute: typeof LearnPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/flashcards/$planId': {
      id: '/flashcards/$planId'
      path: '/flashcards/$planId'
      fullPath: '/flashcards/$planId'
      preLoaderRoute: typeof FlashcardsPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deeplearn/$planId': {
      id: '/deeplearn/$planId'
      path: '/deeplearn/$planId'
      fullPath: '/deeplearn/$planId'
      preLoaderRoute: typeof DeeplearnPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$planId': {
      id: '/certificate/$planId'
      path: '/certificate/$planId'
      fullPath: '/certificate/$planId'
      preLoaderRoute: typeof CertificatePlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive/$sessionId': {
      id: '/adaptive/$sessionId'
      path: '/$sessionId'
      fullPath: '/adaptive/$sessionId'
      preLoaderRoute: typeof AdaptiveSessionIdRouteImport
      parentRoute: typeof AdaptiveRoute
    }
    '/quiz/$planId/$day': {
      id: '/quiz/$planId/$day'
      path: '/quiz/$planId/$day'
      fullPath: '/quiz/$planId/$day'
      preLoaderRoute: typeof QuizPlanIdDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdaptiveRouteChildren {
  AdaptiveSessionIdRoute: typeof AdaptiveSessionIdRoute
  AdaptiveIndexRoute: typeof AdaptiveIndexRoute
}

const AdaptiveRouteChildren: AdaptiveRouteChildren = {
  AdaptiveSessionIdRoute: AdaptiveSessionIdRoute,
  AdaptiveIndexRoute: AdaptiveIndexRoute,
}

const AdaptiveRouteWithChildren = AdaptiveRoute._addFileChildren(
  AdaptiveRouteChildren,
)

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptiveRoute: AdaptiveRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  GroupsRoute: GroupsRouteWithChildren,
  NewRoute: NewRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TryRoute: TryRoute,
  YoutubeToolRoute: YoutubeToolRoute,
  CertificatePlanIdRoute: CertificatePlanIdRoute,
  DeeplearnPlanIdRoute: DeeplearnPlanIdRoute,
  FlashcardsPlanIdRoute: FlashcardsPlanIdRoute,
  LearnPlanIdRoute: LearnPlanIdRoute,
  MindmapPlanIdRoute: MindmapPlanIdRoute,
  SharedTokenRoute: SharedTokenRoute,
  DeeplearnIndexRoute: DeeplearnIndexRoute,
  QuizPlanIdDayRoute: QuizPlanIdDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
